services:
  db:
    image: mariadb:10.7
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: testdb
      MARIADB_USER: testuser
      MARIADB_PASSWORD: testpass
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.2
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: testuser
      PMA_PASSWORD: testpass
    ports:
      - "8081:80"
    volumes:
      - phpmyadmin-data:/sessions
  php:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./practice:/var/www/html
    networks:
      - br0
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - br0
volumes:
  db-data:
  phpmyadmin-data:
networks:
  br0:
    driver: bridge